apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-health
  namespace: camel-k
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: testvv
          image: docker/camel-test/test:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: camel-config
              mountPath: /deployments/application.properties
              subPath: application.properties  
      volumes:
        - name: camel-config
          configMap:
            name: camel-route-config-


